name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ansible-checks:
    uses: exzeo-devops/action-workflows/.github/workflows/ansible-checks.yaml@DOPS-6128
    secrets: inherit