name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ansible-checks:
    uses: exzeo-devops/action-workflows/.github/workflows/ansible-checks.yaml@67557042f6e2306ecc4fd428f60237129b56ed75 # v1.0.26
    secrets: inherit

  tag:
    needs: [ansible-checks]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: exzeo-devops/action-workflows/.github/workflows/github-tag.yaml@67557042f6e2306ecc4fd428f60237129b56ed75 # v1.0.26
    secrets: inherit